server {
    listen 0.0.0.0:8090;
    root www;
    index cgi_demo.html;
    client_max_body_size 1000000;

    location / {
        allow_methods GET;
        index cgi_demo.html;
        autoindex off;
    }

    location /cgi {
        root www/cgi;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_interpreter /usr/bin/python3;
    }
}
