server {
    listen 0.0.0.0:8080;
    root www;
    index index.html;
    client_max_body_size 1000000;

    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    location / {
        allow_methods GET;
        index index.html;
        autoindex off;
    }

    location /post_body {
        allow_methods POST;
    }

    location /directory {
        root YoupiBanane;
        allow_methods GET;
        index youpi.bad_extension;
        autoindex off;
    }

    location /cgi_bla {
        allow_methods POST;
        cgi_extension .bla;
        cgi_interpreter /usr/bin/python3;
    }

    location /images {
        root www/images;
        allow_methods GET;
        autoindex on;
    }

    location /upload {
        allow_methods POST;
        upload_enable on;
        upload_path uploads;
    }

    location /uploads {
        root uploads;
        allow_methods GET DELETE;
        autoindex on;
    }

    location /old {
        return 301 /new.html;
    }

    location /cgi {
        root www/cgi;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_interpreter /usr/bin/python3;
    }
    
}

server {
    listen 8081;
    root www;
    index index.html;
    client_max_body_size 1000000;

    location / {
        allow_methods GET;
        index index.html;
        autoindex off;
    }
}